pipeline:
  name: fis-demo-java
  identifier: fisdemo
  projectIdentifier: fisdemo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deployed
        identifier: deployed
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: fisdemodev
          environment:
            environmentRef: fisdemodev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: kubernetesdeploy
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  notificationRules:
    - name: Teams-notification
      identifier: Teamsnotification
      pipelineEvents:
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: StageFailed
          forStages:
            - deployguestbook
        - type: StageSuccess
          forStages:
            - deployguestbook
      notificationMethod:
        type: MsTeams
        spec:
          userGroups:
            - account._account_all_users
          msTeamKeys:
            - https://slkgroup.webhook.office.com/webhookb2/c4c7884c-0a76-4784-aada-20eada41c4b3@01b695ba-6326-4daf-a9fc-629432404139/IncomingWebhook/89ef89f6d4874d44a1a54f8a19d193c1/18ec1fc8-c6fa-488a-8015-18445aaf9740
      enabled: true
