apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapplication-ui
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: javaapplication-ui
  template:
    metadata:
      labels:
        app: javaapplication-ui
    spec:
      containers:
      - image: ikolaxis/petclinic:java11-openj9
        name: javaapplication-ui
        ports:
        - containerPort: 80
