apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapplication-ui
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: javaapplication-ui
  template:
    metadata:
      labels:
        app: javaapplication-ui
    spec:
      containers:
      - image: slk.jfrog.io/fis-demo-dockerhub/app-image.14.14:latest
        name: javaapplication-ui
        ports:
        - containerPort: 80
