apiVersion: v1
kind: Service
metadata:
  name: hello-virtualization-service
  labels:
    app: hello-virtualization-label
spec: 
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer  
  selector:
    app: hello-virtualization-label
