service:
    name: harness_javaapplicatiom
    identifier: javaapplicatiom
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: javaapplication
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            paths:
                                - harness-deploy/application/deployment.yaml
                                - harness-deploy/application/service.yaml
                            repoName: Demo_app1
                            branch: master
                        skipResourceVersioning: false
                        enable
