# Default values for harness-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: <+artifact.image>
  pullPolicy: IfNotPresent
  tag: latest
  # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []
service:
  type: LoadBalancer
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
